[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build]
  command = "cd backend && npm install && cd ../frontend && npm install && npm run build"
  functions = "backend/netlify/functions"
  publish = "frontend/build"

